language: perl
perl:
  - "5.14"

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libdb-dev
  ## Set a git identity
  - git config --global user.email "travis@example.com"
  - git config --global user.name "Travis PAUSE"
  - mysqld --version
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade
  - sudo service mysql restart
